[tool.mypy]
python_version = "3.10"
disallow_untyped_defs = false
warn_no_return = false
exclude = [
    '^venv/',
    '^app.egg-info/'
]

[tool.black]
line-length = 120
target-version = ['py310']
extend-exclude = '''
^/venv/
'''
